<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Software Testing as a Career_fa fa-star-o</name>
   <tag></tag>
   <elementGuidId>77df4cb7-0d1c-419e-8624-ad62bc8e331d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-star-o</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//footer[@id='g-footer']/div/div/div/div/div/div/div/div[2]/div[2]/div/div/div/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-star-o</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g-footer&quot;)/div[@class=&quot;g-container&quot;]/div[@class=&quot;g-grid&quot;]/div[@class=&quot;g-block size-100&quot;]/div[@class=&quot;g-content&quot;]/div[@class=&quot;platform-content&quot;]/div[@class=&quot;moduletable&quot;]/div[@class=&quot;custom&quot;]/div[@class=&quot;g-grid&quot;]/div[@class=&quot;g-block box4 size-24 hidden-phone&quot;]/div[@class=&quot;g-content g-particle&quot;]/div[@class=&quot;canvas-graph&quot;]/div[@class=&quot;canvas-middle&quot;]/a[1]/i[@class=&quot;fa fa-star-o&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//footer[@id='g-footer']/div/div/div/div/div/div/div/div[2]/div[2]/div/div/div/a/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
   </webElementXpaths>
</WebElementEntity>
